version: '3.9'

services:
  hadoop:
    build: ./hadoop  # Replace with your actual Hadoop Dockerfile path
    container_name: hadoop
    ports:
      - "50070:50070"
      - "8088:8088"
      - "8042:8042"
      - "8020:8020"
      - "9870:9870"
    volumes:
      - hadoop-data:/opt/hadoop/dfs
    networks:
      - hive
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    restart: on-failure

  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: 'metastore_db'
      POSTGRES_USER: 'hive'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - hive-db:/var/lib/postgresql
    networks:
      - hive

  metastore:
    image: apache/hive:${HIVE_VERSION}
    depends_on:
      - postgres
      - hadoop
    restart: unless-stopped
    container_name: metastore
    hostname: metastore
    environment:
      DB_DRIVER: postgres
      SERVICE_NAME: 'metastore'
      SERVICE_OPTS: '-Xmx1G -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
                     -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db
                     -Djavax.jdo.option.ConnectionUserName=hive
                     -Djavax.jdo.option.ConnectionPassword=password'
    ports:
      - '9083:9083'
    volumes:
      - warehouse:/opt/hive/data/warehouse
      - ./postgresql-42.6.2.jar:/opt/hive/lib/postgresql.jar  # Update this line
      - ./hadoop-config:/opt/hadoop/etc/hadoop  # Mount Hadoop config directory
    networks:
      - hive

  hiveserver2:
    build: 
      context: ./hiveserver2
      args:
        HIVE_VERSION: 4.0.0
    depends_on:
      - metastore
    restart: unless-stopped
    container_name: hiveserver2
    environment:
      HIVE_SERVER2_THRIFT_PORT: 10000
      SERVICE_OPTS: '-Xmx1G -Dhive.metastore.uris=thrift://metastore:9083'
      IS_RESUME: 'true'
      SERVICE_NAME: 'hiveserver2'
      HADOOP_CONF_DIR: /opt/hadoop/etc/hadoop
    ports:
      - '10000:10000'
      - '10002:10002'
    volumes:
      - warehouse:/opt/hive/data/warehouse
    networks:
      - hive

volumes:
  hive-db:
  warehouse:
  hadoop-data:

networks:
  hive:
    name: hive
